// Mocks generated by Mockito 5.4.6 from annotations
// in inventory_mesh_box_phone/test/mesh_ui_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i5;

import 'package:flutter_blue_plus/flutter_blue_plus.dart' as _i4;
import 'package:inventory_mesh_box_phone/src/ble_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IBleClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBleClient extends _i1.Mock implements _i2.IBleClient {
  MockIBleClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<int>> get eventStream =>
      (super.noSuchMethod(
            Invocation.getter(#eventStream),
            returnValue: _i3.Stream<List<int>>.empty(),
          )
          as _i3.Stream<List<int>>);

  @override
  _i3.Stream<List<_i4.ScanResult>> get scanResults =>
      (super.noSuchMethod(
            Invocation.getter(#scanResults),
            returnValue: _i3.Stream<List<_i4.ScanResult>>.empty(),
          )
          as _i3.Stream<List<_i4.ScanResult>>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<void> startScan() =>
      (super.noSuchMethod(
            Invocation.method(#startScan, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopScan() =>
      (super.noSuchMethod(
            Invocation.method(#stopScan, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> connect(_i4.BluetoothDevice? device, int? meshPinHash) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [device, meshPinHash]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendCommand(_i5.Uint8List? data) =>
      (super.noSuchMethod(
            Invocation.method(#sendCommand, [data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> requestPriority(_i4.ConnectionPriority? priority) =>
      (super.noSuchMethod(
            Invocation.method(#requestPriority, [priority]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
